(* ::Package:: *)

(* ::Input:: *)
(*Get["SQG1_euclid.wl"];Get["SQG2_euclid.wl"];Get["SQG3_euclid.wl"];*)
(**)
(*(*seed at chosen z;everything in tetrad indices*)*)
(*P0=SeedFromZ[z0];*)
(**)
(*(*optional:sanity check that Euclidean Urbantke gives \[Delta]_AB*)*)
(*VerifySeedEuclid[z0]*)
(**)
(*(*in dynamics,work entirely with tetrad-indexed P;use \[Delta] as the metric*)*)
(*g=IdentityMatrix[4];*)
(*(*proceed with your existing SDE functions that operate on P and Fhat*)*)
(**)
